from django.conf.urls import patterns
from django.conf.urls import url
from django.views.generic import TemplateView


urlpatterns = patterns('recipe.views',
   url(r'^$', 'home', name='home'),
)

urlpatterns += patterns('recipe.views',
    url(r'^api/v1/recipes', 'api_recipes'),
)

urlpatterns += patterns('',
    url(
        r'^fresh-tomato-chile-relish/$',
        TemplateView.as_view(template_name='recipe/fresh-tomato-chile-relish.html'),
        name='fresh-tomato-chile-relish'
    ),
    url(
        r'^red-chile-sauce-with-roasted-tomato/$',
        TemplateView.as_view(template_name='recipe/red-chile-sauce-with-roasted-tomato.html'),
        name='red-chile-sauce-with-roasted-tomato'
    ),
    url(
        r'^quick-cooked-tomato-chile-sauce/$',
        TemplateView.as_view(template_name='recipe/quick-cooked-tomato-chile-sauce.html'),
        name='quick-cooked-tomato-chile-sauce'
    ),
    url(
        r'^chunky-guacamole-avocado-relish/$',
        TemplateView.as_view(template_name='recipe/chunky-guacamole-avocado-relish.html'),
        name='chunky-guacamole-avocado-relish'
    ),
    url(
        r'^relishy-cactus-paddle-salad/$',
        TemplateView.as_view(template_name='recipe/relishy-cactus-paddle-salad.html'),
        name='relishy-cactus-paddle-salad'
    ),
    url(
        r'^pickled-chiles-with-other-vegetables/$',
        TemplateView.as_view(template_name='recipe/pickled-chiles-with-other-vegetables.html'),
        name='pickled-chiles-with-other-vegetables'
    ),
    url(
        r'^pickled-red-onions/$',
        TemplateView.as_view(template_name='recipe/pickled-red-onions.html'),
        name='pickled-red-onions'
    ),
    url(
        r'^homemade-thick-cream/$',
        TemplateView.as_view(template_name='recipe/homemade-thick-cream.html'),
        name='homemade-thick-cream'
    ),
    url(
        r'^tolucan-chile-flavored-sausage/$',
        TemplateView.as_view(template_name='recipe/tolucan-chile-flavored-sausage.html'),
        name='tolucan-chile-flavored-sausage'
    ),
    url(
        r'^sheets-of-pork-in-chile-spice-marinade/$',
        TemplateView.as_view(template_name='recipe/sheets-of-pork-in-chile-spice-marinade.html'),
        name='sheets-of-pork-in-chile-spice-marinade'
    ),
    url(
        r'^shredded-poached-chicken/$',
        TemplateView.as_view(template_name='recipe/shredded-poached-chicken.html'),
        name='shredded-poached-chicken'
    ),
    url(
        r'^broth/$',
        TemplateView.as_view(template_name='recipe/broth.html'),
        name='broth'
    ),
    url(
        r'^fish-broth/$',
        TemplateView.as_view(template_name='recipe/fish-broth.html'),
        name='fish-broth'
    ),
    url(
        r'^red-chile-marinade/$',
        TemplateView.as_view(template_name='recipe/red-chile-marinade.html'),
        name='red-chile-marinade'
    ),
    url(
        r'^yucatecan-mixed-spice-paste/$',
        TemplateView.as_view(template_name='recipe/yucatecan-mixed-spice-paste.html'),
        name='yucatecan-mixed-spice-paste'
    ),
    url(
        r'^corn-tortillas/$',
        TemplateView.as_view(template_name='recipe/corn-tortillas.html'),
        name='corn-tortillas'
    ),
    url(
        r'^wheat-flour-tortillas/$',
        TemplateView.as_view(template_name='recipe/wheat-flour-tortillas.html'),
        name='wheat-flour-tortillas'
    ),
    url(
        r'^crisp-fried-tortillas-and-chips/$',
        TemplateView.as_view(template_name='recipe/crisp-fried-tortillas-and-chips.html'),
        name='crisp-fried-tortillas-and-chips'
    ),
    url(
        r'^lime-marinated-mackerel-with-tomato-and-green-chile/$',
        TemplateView.as_view(template_name='recipe/lime-marinated-mackerel-with-tomato-and-green-chile.html'),
        name='lime-marinated-mackerel-with-tomato-and-green-chile'
    ),
    url(
        r'^mixed-vegetable-salad-with-lime-dressing/$',
        TemplateView.as_view(template_name='recipe/mixed-vegetable-salad-with-lime-dressing.html'),
        name='mixed-vegetable-salad-with-lime-dressing'
    ),
    url(
        r'^nontraditional-salad-dressings/$',
        TemplateView.as_view(template_name='recipe/nontraditional-salad-dressings.html'),
        name='nontraditional-salad-dressings'
    ),
    url(
        r'^roasted-garlic-dressing/$',
        TemplateView.as_view(template_name='recipe/roasted-garlic-dressing.html'),
        name='roasted-garlic-dressing'
    ),
    url(
        r'^garbanzo-vegetable-soup-with-smoky-broth-and-fresh-avocado/$',
        TemplateView.as_view(template_name='recipe/garbanzo-vegetable-soup-with-smoky-broth-and-fresh-avocado.html'),
        name='garbanzo-vegetable-soup-with-smoky-broth-and-fresh-avocado'
    ),
    url(
        r'^fresh-corn-chowder-with-roasted-peppers/$',
        TemplateView.as_view(template_name='recipe/fresh-corn-chowder-with-roasted-peppers.html'),
        name='fresh-corn-chowder-with-roasted-peppers'
    ),
    url(
        r'^spicy-crab-soup/$',
        TemplateView.as_view(template_name='recipe/spicy-crab-soup.html'),
        name='spicy-crab-soup'
    ),
    url(
        r'^shrimp-ball-soup-with-roasted-pepper-and-tomato/$',
        TemplateView.as_view(template_name='recipe/shrimp-ball-soup-with-roasted-pepper-and-tomato.html'),
        name='shrimp-ball-soup-with-roasted-pepper-and-tomato'
    ),
    url(
        r'^pork-chicken-and-hominy-soup-with-ground-pumpkinseeds/$',
        TemplateView.as_view(template_name='recipe/pork-chicken-and-hominy-soup-with-ground-pumpkinseeds.html'),
        name='pork-chicken-and-hominy-soup-with-ground-pumpkinseeds'
    ),
    url(
        r'^pork-and-hominy-soup-with-red-chile-and-fresh-garnishes/$',
        TemplateView.as_view(template_name='recipe/pork-and-hominy-soup-with-red-chile-and-fresh-garnishes.html'),
        name='pork-and-hominy-soup-with-red-chile-and-fresh-garnishes'
    ),
    url(
        r'^red-chile-tripe-soup-with-fresh-garnishes/$',
        TemplateView.as_view(template_name='recipe/red-chile-tripe-soup-with-fresh-garnishes.html'),
        name='red-chile-tripe-soup-with-fresh-garnishes'
    ),
    url(
        r'^ranch-style-eggs-with-tomato-chile-sauce/$',
        TemplateView.as_view(template_name='recipe/ranch-style-eggs-with-tomato-chile-sauce.html'),
        name='ranch-style-eggs-with-tomato-chile-sauce'
    ),
    url(
        r'^scrambled-eggs-with-mexican-flavors/$',
        TemplateView.as_view(template_name='recipe/scrambled-eggs-with-mexican-flavors.html'),
        name='scrambled-eggs-with-mexican-flavors'
    ),
    url(
        r'^scrambled-eggs-with-mexican-sausage/$',
        TemplateView.as_view(template_name='recipe/scrambled-eggs-with-mexican-sausage.html'),
        name='scrambled-eggs-with-mexican-sausage'
    ),
    url(
        r'^shredded-beef-jerky-with-scrambled-eggs-and-chile/$',
        TemplateView.as_view(template_name='recipe/shredded-beef-jerky-with-scrambled-eggs-and-chile.html'),
        name='shredded-beef-jerky-with-scrambled-eggs-and-chile'
    ),
    url(
        r'^tacos/$',
        TemplateView.as_view(template_name='recipe/tacos.html'),
        name='tacos'
    ),
    url(
        r'^soft-tacos-with-fillings-from-the-earthenware-pot-or-griddle/$',
        TemplateView.as_view(template_name='recipe/soft-tacos-with-fillings-from-the-earthenware-pot-or-griddle.html'),
        name='soft-tacos-with-fillings-from-the-earthenware-pot-or-griddle'
    ),
    url(
        r'^scrambled-eggs-and-potatoes-in-tangy-green-sauce/$',
        TemplateView.as_view(template_name='recipe/scrambled-eggs-and-potatoes-in-tangy-green-sauce.html'),
        name='scrambled-eggs-and-potatoes-in-tangy-green-sauce'
    ),
    url(
        r'^shrimp-with-lime-dressing-and-crunchy-vegetables/$',
        TemplateView.as_view(template_name='recipe/shrimp-with-lime-dressing-and-crunchy-vegetables.html'),
        name='shrimp-with-lime-dressing-and-crunchy-vegetables'
    ),
    url(
        r'^northern-style-shredded-beef-with-tomatoes/$',
        TemplateView.as_view(template_name='recipe/northern-style-shredded-beef-with-tomatoes.html'),
        name='northern-style-shredded-beef-with-tomatoes'
    ),
    url(
        r'^minced-pork-with-almonds-raisins-and-sweet-spices/$',
        TemplateView.as_view(template_name='recipe/minced-pork-with-almonds-raisins-and-sweet-spices.html'),
        name='minced-pork-with-almonds-raisins-and-sweet-spices'
    ),
    url(
        r'^potatoes-with-mexican-sausage/$',
        TemplateView.as_view(template_name='recipe/potatoes-with-mexican-sausage.html'),
        name='potatoes-with-mexican-sausage'
    ),
    url(
        r'^slivered-beef-with-well-browned-onions/$',
        TemplateView.as_view(template_name='recipe/slivered-beef-with-well-browned-onions.html'),
        name='slivered-beef-with-well-browned-onions'
    ),
    url(
        r'^pan-fried-chile-marinated-pork/$',
        TemplateView.as_view(template_name='recipe/pan-fried-chile-marinated-pork.html'),
        name='pan-fried-chile-marinated-pork'
    ),
    url(
        r'^soft-tacos-with-fillings-from-the-charcoal-grill/$',
        TemplateView.as_view(template_name='recipe/soft-tacos-with-fillings-from-the-charcoal-grill.html'),
        name='soft-tacos-with-fillings-from-the-charcoal-grill'
    ),
    url(
        r'^charcoal-grilled-skirt-steak/$',
        TemplateView.as_view(template_name='recipe/charcoal-grilled-skirt-steak.html'),
        name='charcoal-grilled-skirt-steak'
    ),
    url(
        r'^crispy-fried-tacos/$',
        TemplateView.as_view(template_name='recipe/crispy-fried-tacos.html'),
        name='crispy-fried-tacos'
    ),
    url(
        r'^burritos-with-spicy-shredded-jerky/$',
        TemplateView.as_view(template_name='recipe/burritos-with-spicy-shredded-jerky.html'),
        name='burritos-with-spicy-shredded-jerky'
    ),
    url(
        r'^turnovers/$',
        TemplateView.as_view(template_name='recipe/turnovers.html'),
        name='turnovers'
    ),
    url(
        r'^turnover-fillings/$',
        TemplateView.as_view(template_name='recipe/turnover-fillings.html'),
        name='turnover-fillings'
    ),
    url(
        r'^potatoes-and-green-chiles/$',
        TemplateView.as_view(template_name='recipe/potatoes-and-green-chiles.html'),
        name='potatoes-and-green-chiles'
    ),
    url(
        r'^brains-with-pungent-mexican-seasonings/$',
        TemplateView.as_view(template_name='recipe/brains-with-pungent-mexican-seasonings.html'),
        name='brains-with-pungent-mexican-seasonings'
    ),
    url(
        r'^stewed-squash-blossoms/$',
        TemplateView.as_view(template_name='recipe/stewed-squash-blossoms.html'),
        name='stewed-squash-blossoms'
    ),
    url(
        r'^stewed-mushrooms-with-onions-and-garlic/$',
        TemplateView.as_view(template_name='recipe/stewed-mushrooms-with-onions-and-garlic.html'),
        name='stewed-mushrooms-with-onions-and-garlic'
    ),
    url(
        r'^crispy-wheat-flour-turnovers-with-well-seasoned-meat/$',
        TemplateView.as_view(template_name='recipe/crispy-wheat-flour-turnovers-with-well-seasoned-meat.html'),
        name='crispy-wheat-flour-turnovers-with-well-seasoned-meat'
    ),
    url(
        r'^enchiladas-and-their-relatives/$',
        TemplateView.as_view(template_name='recipe/enchiladas-and-their-relatives.html'),
        name='enchiladas-and-their-relatives'
    ),
    url(
        r'^red-chile-enchiladas-with-cheese-and-vegetables/$',
        TemplateView.as_view(template_name='recipe/red-chile-enchiladas-with-cheese-and-vegetables.html'),
        name='red-chile-enchiladas-with-cheese-and-vegetables'
    ),
    url(
        r'^stacked-tortillas-with-shark-black-beans-and-tomato-sauce/$',
        TemplateView.as_view(template_name='recipe/stacked-tortillas-with-shark-black-beans-and-tomato-sauce.html'),
        name='stacked-tortillas-with-shark-black-beans-and-tomato-sauce'
    ),
    url(
        r'^other-snacks/$',
        TemplateView.as_view(template_name='recipe/other-snacks.html'),
        name='other-snacks'
    ),
    url(
        r'^chicken-tostadas-with-fresh-vegetables-and-cream/$',
        TemplateView.as_view(template_name='recipe/chicken-tostadas-with-fresh-vegetables-and-cream.html'),
        name='chicken-tostadas-with-fresh-vegetables-and-cream'
    ),
    url(
        r'^chile-marinated-vegetable-tostadas/$',
        TemplateView.as_view(template_name='recipe/chile-marinated-vegetable-tostadas.html'),
        name='chile-marinated-vegetable-tostadas'
    ),
    url(
        r'^half-fried-tortillas-with-black-beans-chicken-and-pickled-onions/$',
        TemplateView.as_view(template_name='recipe/half-fried-tortillas-with-black-beans-chicken-and-pickled-onions.html'),
        name='half-fried-tortillas-with-black-beans-chicken-and-pickled-onions'
    ),
    url(
        r'^quick-simmered-tortilla-casserole-with-green-or-red-sauce/$',
        TemplateView.as_view(template_name='recipe/quick-simmered-tortilla-casserole-with-green-or-red-sauce.html'),
        name='quick-simmered-tortilla-casserole-with-green-or-red-sauce'
    ),
    url(
        r'^layered-tortilla-casserole/$',
        TemplateView.as_view(template_name='recipe/layered-tortilla-casserole.html'),
        name='layered-tortilla-casserole'
    ),
    url(
        r'^tamales/$',
        TemplateView.as_view(template_name='recipe/tamales.html'),
        name='tamales'
    ),
    url(
        r'^tamal-making/$',
        TemplateView.as_view(template_name='recipe/tamal-making.html'),
        name='tamal-making'
    ),
    url(
        r'^fish-fillets-with-fresh-tomatoes-capers-and-olives/$',
        TemplateView.as_view(template_name='recipe/fish-fillets-with-fresh-tomatoes-capers-and-olives.html'),
        name='fish-fillets-with-fresh-tomatoes-capers-and-olives'
    ),
    url(
        r'^quick-fried-fish-with-toasted-garlic/$',
        TemplateView.as_view(template_name='recipe/quick-fried-fish-with-toasted-garlic.html'),
        name='quick-fried-fish-with-toasted-garlic'
    ),
    url(
        r'^quick-fried-fish-with-roasted-peppers-and-thick-cream/$',
        TemplateView.as_view(template_name='recipe/quick-fried-fish-with-roasted-peppers-and-thick-cream.html'),
        name='quick-fried-fish-with-roasted-peppers-and-thick-cream'
    ),
    url(
        r'^chile-bathed-fish-grilled-in-cornhusks/$',
        TemplateView.as_view(template_name='recipe/chile-bathed-fish-grilled-in-cornhusks.html'),
        name='chile-bathed-fish-grilled-in-cornhusks'
    ),
    url(
        r'^oysters-poached-with-mild-vinegar-and-aromatic-spices-tabasco-style/$',
        TemplateView.as_view(template_name='recipe/oysters-poached-with-mild-vinegar-and-aromatic-spices-tabasco-style.html'),
        name='oysters-poached-with-mild-vinegar-and-aromatic-spices-tabasco-style'
    ),
    url(
        r'^duck-in-smooth-pumpkinseed-sauce/$',
        TemplateView.as_view(template_name='recipe/duck-in-smooth-pumpkinseed-sauce.html'),
        name='duck-in-smooth-pumpkinseed-sauce'
    ),
    url(
        r'^charcoal-grilled-chicken-sinaloa-style/$',
        TemplateView.as_view(template_name='recipe/charcoal-grilled-chicken-sinaloa-style.html'),
        name='charcoal-grilled-chicken-sinaloa-style'
    ),
    url(
        r'^chicken-thighs-with-vinegar-oil-and-aromatic-spices/$',
        TemplateView.as_view(template_name='recipe/chicken-thighs-with-vinegar-oil-and-aromatic-spices.html'),
        name='chicken-thighs-with-vinegar-oil-and-aromatic-spices'
    ),
    url(
        r'^red-seasoned-chicken-steamed-in-banana-leaves/$',
        TemplateView.as_view(template_name='recipe/red-seasoned-chicken-steamed-in-banana-leaves.html'),
        name='red-seasoned-chicken-steamed-in-banana-leaves'
    ),
    url(
        r'^chilied-chicken-steamed-with-avocado-leaves/$',
        TemplateView.as_view(template_name='recipe/chilied-chicken-steamed-with-avocado-leaves.html'),
        name='chilied-chicken-steamed-with-avocado-leaves'
    ),
    url(
        r'^broiled-beef-with-classic-accompaniments-tampico-style/$',
        TemplateView.as_view(template_name='recipe/broiled-beef-with-classic-accompaniments-tampico-style.html'),
        name='broiled-beef-with-classic-accompaniments-tampico-style'
    ),
    url(
        r'^pork-stuffed-chiles-in-savory-tomato-sauce/$',
        TemplateView.as_view(template_name='recipe/pork-stuffed-chiles-in-savory-tomato-sauce.html'),
        name='pork-stuffed-chiles-in-savory-tomato-sauce'
    ),
    url(
        r'^pork-with-smoky-tomato-sauce-potatoes-and-avocado/$',
        TemplateView.as_view(template_name='recipe/pork-with-smoky-tomato-sauce-potatoes-and-avocado.html'),
        name='pork-with-smoky-tomato-sauce-potatoes-and-avocado'
    ),
    url(
        r'^meat-in-red-chile-sauce/$',
        TemplateView.as_view(template_name='recipe/meat-in-red-chile-sauce.html'),
        name='meat-in-red-chile-sauce'
    ),
    url(
        r'^savory-golden-country-ribs-with-avocado-relish/$',
        TemplateView.as_view(template_name='recipe/savory-golden-country-ribs-with-avocado-relish.html'),
        name='savory-golden-country-ribs-with-avocado-relish'
    ),
    url(
        r'^charcoal-grilled-pork-loin-with-rich-red-chile-sauce/$',
        TemplateView.as_view(template_name='recipe/charcoal-grilled-pork-loin-with-rich-red-chile-sauce.html'),
        name='charcoal-grilled-pork-loin-with-rich-red-chile-sauce'
    ),
    url(
        r'^slow-steamed-goat-or-lamb-with-mild-chile-seasoning/$',
        TemplateView.as_view(template_name='recipe/slow-steamed-goat-or-lamb-with-mild-chile-seasoning.html'),
        name='slow-steamed-goat-or-lamb-with-mild-chile-seasoning'
    ),
    url(
        r'^mexican-tomato-colored-rice-with-fresh-vegetables/$',
        TemplateView.as_view(template_name='recipe/mexican-tomato-colored-rice-with-fresh-vegetables.html'),
        name='mexican-tomato-colored-rice-with-fresh-vegetables'
    ),
    url(
        r'^white-rice-pilaf-with-corn-roasted-chiles-and-fresh-cheese/$',
        TemplateView.as_view(template_name='recipe/white-rice-pilaf-with-corn-roasted-chiles-and-fresh-cheese.html'),
        name='white-rice-pilaf-with-corn-roasted-chiles-and-fresh-cheese'
    ),
    url(
        r'^herb-green-rice-with-peas/$',
        TemplateView.as_view(template_name='recipe/herb-green-rice-with-peas.html'),
        name='herb-green-rice-with-peas'
    ),
    url(
        r'^brothy-beans/$',
        TemplateView.as_view(template_name='recipe/brothy-beans.html'),
        name='brothy-beans'
    ),
    url(
        r'^fried-beans/$',
        TemplateView.as_view(template_name='recipe/fried-beans.html'),
        name='fried-beans'
    ),
    url(
        r'^beans-with-bacon-roasted-chile-and-fresh-coriander/$',
        TemplateView.as_view(template_name='recipe/beans-with-bacon-roasted-chile-and-fresh-coriander.html'),
        name='beans-with-bacon-roasted-chile-and-fresh-coriander'
    ),
    url(
        r'^charcoal-grilled-corn-with-cream-cheese-and-chile/$',
        TemplateView.as_view(template_name='recipe/charcoal-grilled-corn-with-cream-cheese-and-chile.html'),
        name='charcoal-grilled-corn-with-cream-cheese-and-chile'
    ),
    url(
        r'^zucchini-with-roasted-peppers-corn-and-cream/$',
        TemplateView.as_view(template_name='recipe/zucchini-with-roasted-peppers-corn-and-cream.html'),
        name='zucchini-with-roasted-peppers-corn-and-cream'
    ),
    url(
        r'^quick-fried-zucchini-with-toasted-garlic-and-lime/$',
        TemplateView.as_view(template_name='recipe/quick-fried-zucchini-with-toasted-garlic-and-lime.html'),
        name='quick-fried-zucchini-with-toasted-garlic-and-lime'
    ),
    url(
        r'^swiss-chard-with-tomatoes-and-potatoes/$',
        TemplateView.as_view(template_name='recipe/swiss-chard-with-tomatoes-and-potatoes.html'),
        name='swiss-chard-with-tomatoes-and-potatoes'
    ),
    url(
        r'^charcoal-grilled-baby-onions-with-lime/$',
        TemplateView.as_view(template_name='recipe/charcoal-grilled-baby-onions-with-lime.html'),
        name='charcoal-grilled-baby-onions-with-lime'
    ),
    url(
        r'^roasted-peppers-with-onions-and-herbs/$',
        TemplateView.as_view(template_name='recipe/roasted-peppers-with-onions-and-herbs.html'),
        name='roasted-peppers-with-onions-and-herbs'
    ),
    url(
        r'^vanilla-flavored-caramel-custard/$',
        TemplateView.as_view(template_name='recipe/vanilla-flavored-caramel-custard.html'),
        name='vanilla-flavored-caramel-custard'
    ),
    url(
        r'^creamy-fresh-coconut-dessert/$',
        TemplateView.as_view(template_name='recipe/creamy-fresh-coconut-dessert.html'),
        name='creamy-fresh-coconut-dessert'
    ),
    url(
        r'^mexican-rice-pudding/$',
        TemplateView.as_view(template_name='recipe/mexican-rice-pudding.html'),
        name='mexican-rice-pudding'
    ),
    url(
        r'^sweet-fresh-cheese-pie/$',
        TemplateView.as_view(template_name='recipe/sweet-fresh-cheese-pie.html'),
        name='sweet-fresh-cheese-pie'
    ),
    url(
        r'^pecan-pie-with-raw-sugar-and-spices/$',
        TemplateView.as_view(template_name='recipe/pecan-pie-with-raw-sugar-and-spices.html'),
        name='pecan-pie-with-raw-sugar-and-spices'
    ),
    url(
        r'^goat-milk-caramel-with-spirits/$',
        TemplateView.as_view(template_name='recipe/goat-milk-caramel-with-spirits.html'),
        name='goat-milk-caramel-with-spirits'
    ),
    url(
        r'^buttered-crepes-with-caramel-and-pecans/$',
        TemplateView.as_view(template_name='recipe/buttered-crepes-with-caramel-and-pecans.html'),
        name='buttered-crepes-with-caramel-and-pecans'
    ),
    url(
        r'^butter-fried-plantains-with-thick-cream/$',
        TemplateView.as_view(template_name='recipe/butter-fried-plantains-with-thick-cream.html'),
        name='butter-fried-plantains-with-thick-cream'
    ),
    url(
        r'^poached-guavas-in-spicy-syrup/$',
        TemplateView.as_view(template_name='recipe/poached-guavas-in-spicy-syrup.html'),
        name='poached-guavas-in-spicy-syrup'
    ),
    url(
        r'^custard-ice-cream-with-cinnamon-and-vanilla/$',
        TemplateView.as_view(template_name='recipe/custard-ice-cream-with-cinnamon-and-vanilla.html'),
        name='custard-ice-cream-with-cinnamon-and-vanilla'
    ),
    url(
        r'^fresh-prickly-pear-ice/$',
        TemplateView.as_view(template_name='recipe/fresh-prickly-pear-ice.html'),
        name='fresh-prickly-pear-ice'
    ),
    url(
        r'^jamaica-flower-cooler/$',
        TemplateView.as_view(template_name='recipe/jamaica-flower-cooler.html'),
        name='jamaica-flower-cooler'
    ),
    url(
        r'^tamarind-cooler/$',
        TemplateView.as_view(template_name='recipe/tamarind-cooler.html'),
        name='tamarind-cooler'
    ),
    url(
        r'^almond-rice-cooler/$',
        TemplateView.as_view(template_name='recipe/almond-rice-cooler.html'),
        name='almond-rice-cooler'
    ),
    url(
        r'^lime-zest-cooler/$',
        TemplateView.as_view(template_name='recipe/lime-zest-cooler.html'),
        name='lime-zest-cooler'
    ),
    url(
        r'^sparkling-limeade/$',
        TemplateView.as_view(template_name='recipe/sparkling-limeade.html'),
        name='sparkling-limeade'
    ),
    url(
        r'^fruit-and-milk-smoothy/$',
        TemplateView.as_view(template_name='recipe/fruit-and-milk-smoothy.html'),
        name='fruit-and-milk-smoothy'
    ),
    url(
        r'^making-oaxacan-chocolate/$',
        TemplateView.as_view(template_name='recipe/making-oaxacan-chocolate.html'),
        name='making-oaxacan-chocolate'
    ),
    url(
        r'^cinnamon-flavored-hot-chocolate/$',
        TemplateView.as_view(template_name='recipe/cinnamon-flavored-hot-chocolate.html'),
        name='cinnamon-flavored-hot-chocolate'
    ),
    url(
        r'^pot-brewed-coffee-with-raw-sugar-and-spices/$',
        TemplateView.as_view(template_name='recipe/pot-brewed-coffee-with-raw-sugar-and-spices.html'),
        name='pot-brewed-coffee-with-raw-sugar-and-spices'
    ),
    url(
        r'^tequila-shooters-with-spicy-chaser/$',
        TemplateView.as_view(template_name='recipe/tequila-shooters-with-spicy-chaser.html'),
        name='tequila-shooters-with-spicy-chaser'
    ),
    url(
        r'^tequila-lime-cocktail/$',
        TemplateView.as_view(template_name='recipe/tequila-lime-cocktail.html'),
        name='tequila-lime-cocktail'
    ),
    url(
        r'^red-wine-cooler-with-fresh-lime/$',
        TemplateView.as_view(template_name='recipe/red-wine-cooler-with-fresh-lime.html'),
        name='red-wine-cooler-with-fresh-lime'
    ),
)